/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DocsIndexRouteImport } from './routes/docs.index'
import { Route as DocsComponentsTooltipRouteImport } from './routes/docs.components.tooltip'
import { Route as DocsComponentsToggleGroupRouteImport } from './routes/docs.components.toggle-group'
import { Route as DocsComponentsToggleRouteImport } from './routes/docs.components.toggle'
import { Route as DocsComponentsToastRouteImport } from './routes/docs.components.toast'
import { Route as DocsComponentsTextareaRouteImport } from './routes/docs.components.textarea'
import { Route as DocsComponentsTextRouteImport } from './routes/docs.components.text'
import { Route as DocsComponentsTagRouteImport } from './routes/docs.components.tag'
import { Route as DocsComponentsTabsRouteImport } from './routes/docs.components.tabs'
import { Route as DocsComponentsTableRouteImport } from './routes/docs.components.table'
import { Route as DocsComponentsSwitchRouteImport } from './routes/docs.components.switch'
import { Route as DocsComponentsStepsRouteImport } from './routes/docs.components.steps'
import { Route as DocsComponentsSkeletonRouteImport } from './routes/docs.components.skeleton'
import { Route as DocsComponentsSeparatorRouteImport } from './routes/docs.components.separator'
import { Route as DocsComponentsSelectRouteImport } from './routes/docs.components.select'
import { Route as DocsComponentsRatingRouteImport } from './routes/docs.components.rating'
import { Route as DocsComponentsRadioCardRouteImport } from './routes/docs.components.radio-card'
import { Route as DocsComponentsRadioRouteImport } from './routes/docs.components.radio'
import { Route as DocsComponentsQrCodeRouteImport } from './routes/docs.components.qr-code'
import { Route as DocsComponentsProgressCircleRouteImport } from './routes/docs.components.progress-circle'
import { Route as DocsComponentsProgressRouteImport } from './routes/docs.components.progress'
import { Route as DocsComponentsPopoverRouteImport } from './routes/docs.components.popover'
import { Route as DocsComponentsPinInputRouteImport } from './routes/docs.components.pin-input'
import { Route as DocsComponentsPasswordInputRouteImport } from './routes/docs.components.password-input'
import { Route as DocsComponentsPaginationRouteImport } from './routes/docs.components.pagination'
import { Route as DocsComponentsMenuRouteImport } from './routes/docs.components.menu'
import { Route as DocsComponentsInputRouteImport } from './routes/docs.components.input'
import { Route as DocsComponentsHighlightRouteImport } from './routes/docs.components.highlight'
import { Route as DocsComponentsHeadingRouteImport } from './routes/docs.components.heading'
import { Route as DocsComponentsFieldRouteImport } from './routes/docs.components.field'
import { Route as DocsComponentsDialogRouteImport } from './routes/docs.components.dialog'
import { Route as DocsComponentsDatePickerRouteImport } from './routes/docs.components.date-picker'
import { Route as DocsComponentsComboboxRouteImport } from './routes/docs.components.combobox'
import { Route as DocsComponentsCollapsibleRouteImport } from './routes/docs.components.collapsible'
import { Route as DocsComponentsCodeBlockRouteImport } from './routes/docs.components.code-block'
import { Route as DocsComponentsClipboardRouteImport } from './routes/docs.components.clipboard'
import { Route as DocsComponentsCheckboxCardRouteImport } from './routes/docs.components.checkbox-card'
import { Route as DocsComponentsCheckboxRouteImport } from './routes/docs.components.checkbox'
import { Route as DocsComponentsCarouselRouteImport } from './routes/docs.components.carousel'
import { Route as DocsComponentsCardRouteImport } from './routes/docs.components.card'
import { Route as DocsComponentsButtonRouteImport } from './routes/docs.components.button'
import { Route as DocsComponentsBreadcrumbRouteImport } from './routes/docs.components.breadcrumb'
import { Route as DocsComponentsAvatarRouteImport } from './routes/docs.components.avatar'
import { Route as DocsComponentsAlertRouteImport } from './routes/docs.components.alert'
import { Route as DocsComponentsAccordionRouteImport } from './routes/docs.components.accordion'
import { Route as DocsChartsAreaChartRouteImport } from './routes/docs.charts.area-chart'
import { Route as DocsFirstStepsIntroductionIndexRouteImport } from './routes/docs.first-steps.introduction.index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsIndexRoute = DocsIndexRouteImport.update({
  id: '/docs/',
  path: '/docs/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsComponentsTooltipRoute = DocsComponentsTooltipRouteImport.update({
  id: '/docs/components/tooltip',
  path: '/docs/components/tooltip',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsComponentsToggleGroupRoute =
  DocsComponentsToggleGroupRouteImport.update({
    id: '/docs/components/toggle-group',
    path: '/docs/components/toggle-group',
    getParentRoute: () => rootRouteImport,
  } as any)
const DocsComponentsToggleRoute = DocsComponentsToggleRouteImport.update({
  id: '/docs/components/toggle',
  path: '/docs/components/toggle',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsComponentsToastRoute = DocsComponentsToastRouteImport.update({
  id: '/docs/components/toast',
  path: '/docs/components/toast',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsComponentsTextareaRoute = DocsComponentsTextareaRouteImport.update({
  id: '/docs/components/textarea',
  path: '/docs/components/textarea',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsComponentsTextRoute = DocsComponentsTextRouteImport.update({
  id: '/docs/components/text',
  path: '/docs/components/text',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsComponentsTagRoute = DocsComponentsTagRouteImport.update({
  id: '/docs/components/tag',
  path: '/docs/components/tag',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsComponentsTabsRoute = DocsComponentsTabsRouteImport.update({
  id: '/docs/components/tabs',
  path: '/docs/components/tabs',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsComponentsTableRoute = DocsComponentsTableRouteImport.update({
  id: '/docs/components/table',
  path: '/docs/components/table',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsComponentsSwitchRoute = DocsComponentsSwitchRouteImport.update({
  id: '/docs/components/switch',
  path: '/docs/components/switch',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsComponentsStepsRoute = DocsComponentsStepsRouteImport.update({
  id: '/docs/components/steps',
  path: '/docs/components/steps',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsComponentsSkeletonRoute = DocsComponentsSkeletonRouteImport.update({
  id: '/docs/components/skeleton',
  path: '/docs/components/skeleton',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsComponentsSeparatorRoute = DocsComponentsSeparatorRouteImport.update({
  id: '/docs/components/separator',
  path: '/docs/components/separator',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsComponentsSelectRoute = DocsComponentsSelectRouteImport.update({
  id: '/docs/components/select',
  path: '/docs/components/select',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsComponentsRatingRoute = DocsComponentsRatingRouteImport.update({
  id: '/docs/components/rating',
  path: '/docs/components/rating',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsComponentsRadioCardRoute = DocsComponentsRadioCardRouteImport.update({
  id: '/docs/components/radio-card',
  path: '/docs/components/radio-card',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsComponentsRadioRoute = DocsComponentsRadioRouteImport.update({
  id: '/docs/components/radio',
  path: '/docs/components/radio',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsComponentsQrCodeRoute = DocsComponentsQrCodeRouteImport.update({
  id: '/docs/components/qr-code',
  path: '/docs/components/qr-code',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsComponentsProgressCircleRoute =
  DocsComponentsProgressCircleRouteImport.update({
    id: '/docs/components/progress-circle',
    path: '/docs/components/progress-circle',
    getParentRoute: () => rootRouteImport,
  } as any)
const DocsComponentsProgressRoute = DocsComponentsProgressRouteImport.update({
  id: '/docs/components/progress',
  path: '/docs/components/progress',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsComponentsPopoverRoute = DocsComponentsPopoverRouteImport.update({
  id: '/docs/components/popover',
  path: '/docs/components/popover',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsComponentsPinInputRoute = DocsComponentsPinInputRouteImport.update({
  id: '/docs/components/pin-input',
  path: '/docs/components/pin-input',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsComponentsPasswordInputRoute =
  DocsComponentsPasswordInputRouteImport.update({
    id: '/docs/components/password-input',
    path: '/docs/components/password-input',
    getParentRoute: () => rootRouteImport,
  } as any)
const DocsComponentsPaginationRoute =
  DocsComponentsPaginationRouteImport.update({
    id: '/docs/components/pagination',
    path: '/docs/components/pagination',
    getParentRoute: () => rootRouteImport,
  } as any)
const DocsComponentsMenuRoute = DocsComponentsMenuRouteImport.update({
  id: '/docs/components/menu',
  path: '/docs/components/menu',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsComponentsInputRoute = DocsComponentsInputRouteImport.update({
  id: '/docs/components/input',
  path: '/docs/components/input',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsComponentsHighlightRoute = DocsComponentsHighlightRouteImport.update({
  id: '/docs/components/highlight',
  path: '/docs/components/highlight',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsComponentsHeadingRoute = DocsComponentsHeadingRouteImport.update({
  id: '/docs/components/heading',
  path: '/docs/components/heading',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsComponentsFieldRoute = DocsComponentsFieldRouteImport.update({
  id: '/docs/components/field',
  path: '/docs/components/field',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsComponentsDialogRoute = DocsComponentsDialogRouteImport.update({
  id: '/docs/components/dialog',
  path: '/docs/components/dialog',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsComponentsDatePickerRoute =
  DocsComponentsDatePickerRouteImport.update({
    id: '/docs/components/date-picker',
    path: '/docs/components/date-picker',
    getParentRoute: () => rootRouteImport,
  } as any)
const DocsComponentsComboboxRoute = DocsComponentsComboboxRouteImport.update({
  id: '/docs/components/combobox',
  path: '/docs/components/combobox',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsComponentsCollapsibleRoute =
  DocsComponentsCollapsibleRouteImport.update({
    id: '/docs/components/collapsible',
    path: '/docs/components/collapsible',
    getParentRoute: () => rootRouteImport,
  } as any)
const DocsComponentsCodeBlockRoute = DocsComponentsCodeBlockRouteImport.update({
  id: '/docs/components/code-block',
  path: '/docs/components/code-block',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsComponentsClipboardRoute = DocsComponentsClipboardRouteImport.update({
  id: '/docs/components/clipboard',
  path: '/docs/components/clipboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsComponentsCheckboxCardRoute =
  DocsComponentsCheckboxCardRouteImport.update({
    id: '/docs/components/checkbox-card',
    path: '/docs/components/checkbox-card',
    getParentRoute: () => rootRouteImport,
  } as any)
const DocsComponentsCheckboxRoute = DocsComponentsCheckboxRouteImport.update({
  id: '/docs/components/checkbox',
  path: '/docs/components/checkbox',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsComponentsCarouselRoute = DocsComponentsCarouselRouteImport.update({
  id: '/docs/components/carousel',
  path: '/docs/components/carousel',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsComponentsCardRoute = DocsComponentsCardRouteImport.update({
  id: '/docs/components/card',
  path: '/docs/components/card',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsComponentsButtonRoute = DocsComponentsButtonRouteImport.update({
  id: '/docs/components/button',
  path: '/docs/components/button',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsComponentsBreadcrumbRoute =
  DocsComponentsBreadcrumbRouteImport.update({
    id: '/docs/components/breadcrumb',
    path: '/docs/components/breadcrumb',
    getParentRoute: () => rootRouteImport,
  } as any)
const DocsComponentsAvatarRoute = DocsComponentsAvatarRouteImport.update({
  id: '/docs/components/avatar',
  path: '/docs/components/avatar',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsComponentsAlertRoute = DocsComponentsAlertRouteImport.update({
  id: '/docs/components/alert',
  path: '/docs/components/alert',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsComponentsAccordionRoute = DocsComponentsAccordionRouteImport.update({
  id: '/docs/components/accordion',
  path: '/docs/components/accordion',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsChartsAreaChartRoute = DocsChartsAreaChartRouteImport.update({
  id: '/docs/charts/area-chart',
  path: '/docs/charts/area-chart',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsFirstStepsIntroductionIndexRoute =
  DocsFirstStepsIntroductionIndexRouteImport.update({
    id: '/docs/first-steps/introduction/',
    path: '/docs/first-steps/introduction/',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/docs/': typeof DocsIndexRoute
  '/docs/charts/area-chart': typeof DocsChartsAreaChartRoute
  '/docs/components/accordion': typeof DocsComponentsAccordionRoute
  '/docs/components/alert': typeof DocsComponentsAlertRoute
  '/docs/components/avatar': typeof DocsComponentsAvatarRoute
  '/docs/components/breadcrumb': typeof DocsComponentsBreadcrumbRoute
  '/docs/components/button': typeof DocsComponentsButtonRoute
  '/docs/components/card': typeof DocsComponentsCardRoute
  '/docs/components/carousel': typeof DocsComponentsCarouselRoute
  '/docs/components/checkbox': typeof DocsComponentsCheckboxRoute
  '/docs/components/checkbox-card': typeof DocsComponentsCheckboxCardRoute
  '/docs/components/clipboard': typeof DocsComponentsClipboardRoute
  '/docs/components/code-block': typeof DocsComponentsCodeBlockRoute
  '/docs/components/collapsible': typeof DocsComponentsCollapsibleRoute
  '/docs/components/combobox': typeof DocsComponentsComboboxRoute
  '/docs/components/date-picker': typeof DocsComponentsDatePickerRoute
  '/docs/components/dialog': typeof DocsComponentsDialogRoute
  '/docs/components/field': typeof DocsComponentsFieldRoute
  '/docs/components/heading': typeof DocsComponentsHeadingRoute
  '/docs/components/highlight': typeof DocsComponentsHighlightRoute
  '/docs/components/input': typeof DocsComponentsInputRoute
  '/docs/components/menu': typeof DocsComponentsMenuRoute
  '/docs/components/pagination': typeof DocsComponentsPaginationRoute
  '/docs/components/password-input': typeof DocsComponentsPasswordInputRoute
  '/docs/components/pin-input': typeof DocsComponentsPinInputRoute
  '/docs/components/popover': typeof DocsComponentsPopoverRoute
  '/docs/components/progress': typeof DocsComponentsProgressRoute
  '/docs/components/progress-circle': typeof DocsComponentsProgressCircleRoute
  '/docs/components/qr-code': typeof DocsComponentsQrCodeRoute
  '/docs/components/radio': typeof DocsComponentsRadioRoute
  '/docs/components/radio-card': typeof DocsComponentsRadioCardRoute
  '/docs/components/rating': typeof DocsComponentsRatingRoute
  '/docs/components/select': typeof DocsComponentsSelectRoute
  '/docs/components/separator': typeof DocsComponentsSeparatorRoute
  '/docs/components/skeleton': typeof DocsComponentsSkeletonRoute
  '/docs/components/steps': typeof DocsComponentsStepsRoute
  '/docs/components/switch': typeof DocsComponentsSwitchRoute
  '/docs/components/table': typeof DocsComponentsTableRoute
  '/docs/components/tabs': typeof DocsComponentsTabsRoute
  '/docs/components/tag': typeof DocsComponentsTagRoute
  '/docs/components/text': typeof DocsComponentsTextRoute
  '/docs/components/textarea': typeof DocsComponentsTextareaRoute
  '/docs/components/toast': typeof DocsComponentsToastRoute
  '/docs/components/toggle': typeof DocsComponentsToggleRoute
  '/docs/components/toggle-group': typeof DocsComponentsToggleGroupRoute
  '/docs/components/tooltip': typeof DocsComponentsTooltipRoute
  '/docs/first-steps/introduction/': typeof DocsFirstStepsIntroductionIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/docs': typeof DocsIndexRoute
  '/docs/charts/area-chart': typeof DocsChartsAreaChartRoute
  '/docs/components/accordion': typeof DocsComponentsAccordionRoute
  '/docs/components/alert': typeof DocsComponentsAlertRoute
  '/docs/components/avatar': typeof DocsComponentsAvatarRoute
  '/docs/components/breadcrumb': typeof DocsComponentsBreadcrumbRoute
  '/docs/components/button': typeof DocsComponentsButtonRoute
  '/docs/components/card': typeof DocsComponentsCardRoute
  '/docs/components/carousel': typeof DocsComponentsCarouselRoute
  '/docs/components/checkbox': typeof DocsComponentsCheckboxRoute
  '/docs/components/checkbox-card': typeof DocsComponentsCheckboxCardRoute
  '/docs/components/clipboard': typeof DocsComponentsClipboardRoute
  '/docs/components/code-block': typeof DocsComponentsCodeBlockRoute
  '/docs/components/collapsible': typeof DocsComponentsCollapsibleRoute
  '/docs/components/combobox': typeof DocsComponentsComboboxRoute
  '/docs/components/date-picker': typeof DocsComponentsDatePickerRoute
  '/docs/components/dialog': typeof DocsComponentsDialogRoute
  '/docs/components/field': typeof DocsComponentsFieldRoute
  '/docs/components/heading': typeof DocsComponentsHeadingRoute
  '/docs/components/highlight': typeof DocsComponentsHighlightRoute
  '/docs/components/input': typeof DocsComponentsInputRoute
  '/docs/components/menu': typeof DocsComponentsMenuRoute
  '/docs/components/pagination': typeof DocsComponentsPaginationRoute
  '/docs/components/password-input': typeof DocsComponentsPasswordInputRoute
  '/docs/components/pin-input': typeof DocsComponentsPinInputRoute
  '/docs/components/popover': typeof DocsComponentsPopoverRoute
  '/docs/components/progress': typeof DocsComponentsProgressRoute
  '/docs/components/progress-circle': typeof DocsComponentsProgressCircleRoute
  '/docs/components/qr-code': typeof DocsComponentsQrCodeRoute
  '/docs/components/radio': typeof DocsComponentsRadioRoute
  '/docs/components/radio-card': typeof DocsComponentsRadioCardRoute
  '/docs/components/rating': typeof DocsComponentsRatingRoute
  '/docs/components/select': typeof DocsComponentsSelectRoute
  '/docs/components/separator': typeof DocsComponentsSeparatorRoute
  '/docs/components/skeleton': typeof DocsComponentsSkeletonRoute
  '/docs/components/steps': typeof DocsComponentsStepsRoute
  '/docs/components/switch': typeof DocsComponentsSwitchRoute
  '/docs/components/table': typeof DocsComponentsTableRoute
  '/docs/components/tabs': typeof DocsComponentsTabsRoute
  '/docs/components/tag': typeof DocsComponentsTagRoute
  '/docs/components/text': typeof DocsComponentsTextRoute
  '/docs/components/textarea': typeof DocsComponentsTextareaRoute
  '/docs/components/toast': typeof DocsComponentsToastRoute
  '/docs/components/toggle': typeof DocsComponentsToggleRoute
  '/docs/components/toggle-group': typeof DocsComponentsToggleGroupRoute
  '/docs/components/tooltip': typeof DocsComponentsTooltipRoute
  '/docs/first-steps/introduction': typeof DocsFirstStepsIntroductionIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/docs/': typeof DocsIndexRoute
  '/docs/charts/area-chart': typeof DocsChartsAreaChartRoute
  '/docs/components/accordion': typeof DocsComponentsAccordionRoute
  '/docs/components/alert': typeof DocsComponentsAlertRoute
  '/docs/components/avatar': typeof DocsComponentsAvatarRoute
  '/docs/components/breadcrumb': typeof DocsComponentsBreadcrumbRoute
  '/docs/components/button': typeof DocsComponentsButtonRoute
  '/docs/components/card': typeof DocsComponentsCardRoute
  '/docs/components/carousel': typeof DocsComponentsCarouselRoute
  '/docs/components/checkbox': typeof DocsComponentsCheckboxRoute
  '/docs/components/checkbox-card': typeof DocsComponentsCheckboxCardRoute
  '/docs/components/clipboard': typeof DocsComponentsClipboardRoute
  '/docs/components/code-block': typeof DocsComponentsCodeBlockRoute
  '/docs/components/collapsible': typeof DocsComponentsCollapsibleRoute
  '/docs/components/combobox': typeof DocsComponentsComboboxRoute
  '/docs/components/date-picker': typeof DocsComponentsDatePickerRoute
  '/docs/components/dialog': typeof DocsComponentsDialogRoute
  '/docs/components/field': typeof DocsComponentsFieldRoute
  '/docs/components/heading': typeof DocsComponentsHeadingRoute
  '/docs/components/highlight': typeof DocsComponentsHighlightRoute
  '/docs/components/input': typeof DocsComponentsInputRoute
  '/docs/components/menu': typeof DocsComponentsMenuRoute
  '/docs/components/pagination': typeof DocsComponentsPaginationRoute
  '/docs/components/password-input': typeof DocsComponentsPasswordInputRoute
  '/docs/components/pin-input': typeof DocsComponentsPinInputRoute
  '/docs/components/popover': typeof DocsComponentsPopoverRoute
  '/docs/components/progress': typeof DocsComponentsProgressRoute
  '/docs/components/progress-circle': typeof DocsComponentsProgressCircleRoute
  '/docs/components/qr-code': typeof DocsComponentsQrCodeRoute
  '/docs/components/radio': typeof DocsComponentsRadioRoute
  '/docs/components/radio-card': typeof DocsComponentsRadioCardRoute
  '/docs/components/rating': typeof DocsComponentsRatingRoute
  '/docs/components/select': typeof DocsComponentsSelectRoute
  '/docs/components/separator': typeof DocsComponentsSeparatorRoute
  '/docs/components/skeleton': typeof DocsComponentsSkeletonRoute
  '/docs/components/steps': typeof DocsComponentsStepsRoute
  '/docs/components/switch': typeof DocsComponentsSwitchRoute
  '/docs/components/table': typeof DocsComponentsTableRoute
  '/docs/components/tabs': typeof DocsComponentsTabsRoute
  '/docs/components/tag': typeof DocsComponentsTagRoute
  '/docs/components/text': typeof DocsComponentsTextRoute
  '/docs/components/textarea': typeof DocsComponentsTextareaRoute
  '/docs/components/toast': typeof DocsComponentsToastRoute
  '/docs/components/toggle': typeof DocsComponentsToggleRoute
  '/docs/components/toggle-group': typeof DocsComponentsToggleGroupRoute
  '/docs/components/tooltip': typeof DocsComponentsTooltipRoute
  '/docs/first-steps/introduction/': typeof DocsFirstStepsIntroductionIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/docs/'
    | '/docs/charts/area-chart'
    | '/docs/components/accordion'
    | '/docs/components/alert'
    | '/docs/components/avatar'
    | '/docs/components/breadcrumb'
    | '/docs/components/button'
    | '/docs/components/card'
    | '/docs/components/carousel'
    | '/docs/components/checkbox'
    | '/docs/components/checkbox-card'
    | '/docs/components/clipboard'
    | '/docs/components/code-block'
    | '/docs/components/collapsible'
    | '/docs/components/combobox'
    | '/docs/components/date-picker'
    | '/docs/components/dialog'
    | '/docs/components/field'
    | '/docs/components/heading'
    | '/docs/components/highlight'
    | '/docs/components/input'
    | '/docs/components/menu'
    | '/docs/components/pagination'
    | '/docs/components/password-input'
    | '/docs/components/pin-input'
    | '/docs/components/popover'
    | '/docs/components/progress'
    | '/docs/components/progress-circle'
    | '/docs/components/qr-code'
    | '/docs/components/radio'
    | '/docs/components/radio-card'
    | '/docs/components/rating'
    | '/docs/components/select'
    | '/docs/components/separator'
    | '/docs/components/skeleton'
    | '/docs/components/steps'
    | '/docs/components/switch'
    | '/docs/components/table'
    | '/docs/components/tabs'
    | '/docs/components/tag'
    | '/docs/components/text'
    | '/docs/components/textarea'
    | '/docs/components/toast'
    | '/docs/components/toggle'
    | '/docs/components/toggle-group'
    | '/docs/components/tooltip'
    | '/docs/first-steps/introduction/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/docs'
    | '/docs/charts/area-chart'
    | '/docs/components/accordion'
    | '/docs/components/alert'
    | '/docs/components/avatar'
    | '/docs/components/breadcrumb'
    | '/docs/components/button'
    | '/docs/components/card'
    | '/docs/components/carousel'
    | '/docs/components/checkbox'
    | '/docs/components/checkbox-card'
    | '/docs/components/clipboard'
    | '/docs/components/code-block'
    | '/docs/components/collapsible'
    | '/docs/components/combobox'
    | '/docs/components/date-picker'
    | '/docs/components/dialog'
    | '/docs/components/field'
    | '/docs/components/heading'
    | '/docs/components/highlight'
    | '/docs/components/input'
    | '/docs/components/menu'
    | '/docs/components/pagination'
    | '/docs/components/password-input'
    | '/docs/components/pin-input'
    | '/docs/components/popover'
    | '/docs/components/progress'
    | '/docs/components/progress-circle'
    | '/docs/components/qr-code'
    | '/docs/components/radio'
    | '/docs/components/radio-card'
    | '/docs/components/rating'
    | '/docs/components/select'
    | '/docs/components/separator'
    | '/docs/components/skeleton'
    | '/docs/components/steps'
    | '/docs/components/switch'
    | '/docs/components/table'
    | '/docs/components/tabs'
    | '/docs/components/tag'
    | '/docs/components/text'
    | '/docs/components/textarea'
    | '/docs/components/toast'
    | '/docs/components/toggle'
    | '/docs/components/toggle-group'
    | '/docs/components/tooltip'
    | '/docs/first-steps/introduction'
  id:
    | '__root__'
    | '/'
    | '/docs/'
    | '/docs/charts/area-chart'
    | '/docs/components/accordion'
    | '/docs/components/alert'
    | '/docs/components/avatar'
    | '/docs/components/breadcrumb'
    | '/docs/components/button'
    | '/docs/components/card'
    | '/docs/components/carousel'
    | '/docs/components/checkbox'
    | '/docs/components/checkbox-card'
    | '/docs/components/clipboard'
    | '/docs/components/code-block'
    | '/docs/components/collapsible'
    | '/docs/components/combobox'
    | '/docs/components/date-picker'
    | '/docs/components/dialog'
    | '/docs/components/field'
    | '/docs/components/heading'
    | '/docs/components/highlight'
    | '/docs/components/input'
    | '/docs/components/menu'
    | '/docs/components/pagination'
    | '/docs/components/password-input'
    | '/docs/components/pin-input'
    | '/docs/components/popover'
    | '/docs/components/progress'
    | '/docs/components/progress-circle'
    | '/docs/components/qr-code'
    | '/docs/components/radio'
    | '/docs/components/radio-card'
    | '/docs/components/rating'
    | '/docs/components/select'
    | '/docs/components/separator'
    | '/docs/components/skeleton'
    | '/docs/components/steps'
    | '/docs/components/switch'
    | '/docs/components/table'
    | '/docs/components/tabs'
    | '/docs/components/tag'
    | '/docs/components/text'
    | '/docs/components/textarea'
    | '/docs/components/toast'
    | '/docs/components/toggle'
    | '/docs/components/toggle-group'
    | '/docs/components/tooltip'
    | '/docs/first-steps/introduction/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DocsIndexRoute: typeof DocsIndexRoute
  DocsChartsAreaChartRoute: typeof DocsChartsAreaChartRoute
  DocsComponentsAccordionRoute: typeof DocsComponentsAccordionRoute
  DocsComponentsAlertRoute: typeof DocsComponentsAlertRoute
  DocsComponentsAvatarRoute: typeof DocsComponentsAvatarRoute
  DocsComponentsBreadcrumbRoute: typeof DocsComponentsBreadcrumbRoute
  DocsComponentsButtonRoute: typeof DocsComponentsButtonRoute
  DocsComponentsCardRoute: typeof DocsComponentsCardRoute
  DocsComponentsCarouselRoute: typeof DocsComponentsCarouselRoute
  DocsComponentsCheckboxRoute: typeof DocsComponentsCheckboxRoute
  DocsComponentsCheckboxCardRoute: typeof DocsComponentsCheckboxCardRoute
  DocsComponentsClipboardRoute: typeof DocsComponentsClipboardRoute
  DocsComponentsCodeBlockRoute: typeof DocsComponentsCodeBlockRoute
  DocsComponentsCollapsibleRoute: typeof DocsComponentsCollapsibleRoute
  DocsComponentsComboboxRoute: typeof DocsComponentsComboboxRoute
  DocsComponentsDatePickerRoute: typeof DocsComponentsDatePickerRoute
  DocsComponentsDialogRoute: typeof DocsComponentsDialogRoute
  DocsComponentsFieldRoute: typeof DocsComponentsFieldRoute
  DocsComponentsHeadingRoute: typeof DocsComponentsHeadingRoute
  DocsComponentsHighlightRoute: typeof DocsComponentsHighlightRoute
  DocsComponentsInputRoute: typeof DocsComponentsInputRoute
  DocsComponentsMenuRoute: typeof DocsComponentsMenuRoute
  DocsComponentsPaginationRoute: typeof DocsComponentsPaginationRoute
  DocsComponentsPasswordInputRoute: typeof DocsComponentsPasswordInputRoute
  DocsComponentsPinInputRoute: typeof DocsComponentsPinInputRoute
  DocsComponentsPopoverRoute: typeof DocsComponentsPopoverRoute
  DocsComponentsProgressRoute: typeof DocsComponentsProgressRoute
  DocsComponentsProgressCircleRoute: typeof DocsComponentsProgressCircleRoute
  DocsComponentsQrCodeRoute: typeof DocsComponentsQrCodeRoute
  DocsComponentsRadioRoute: typeof DocsComponentsRadioRoute
  DocsComponentsRadioCardRoute: typeof DocsComponentsRadioCardRoute
  DocsComponentsRatingRoute: typeof DocsComponentsRatingRoute
  DocsComponentsSelectRoute: typeof DocsComponentsSelectRoute
  DocsComponentsSeparatorRoute: typeof DocsComponentsSeparatorRoute
  DocsComponentsSkeletonRoute: typeof DocsComponentsSkeletonRoute
  DocsComponentsStepsRoute: typeof DocsComponentsStepsRoute
  DocsComponentsSwitchRoute: typeof DocsComponentsSwitchRoute
  DocsComponentsTableRoute: typeof DocsComponentsTableRoute
  DocsComponentsTabsRoute: typeof DocsComponentsTabsRoute
  DocsComponentsTagRoute: typeof DocsComponentsTagRoute
  DocsComponentsTextRoute: typeof DocsComponentsTextRoute
  DocsComponentsTextareaRoute: typeof DocsComponentsTextareaRoute
  DocsComponentsToastRoute: typeof DocsComponentsToastRoute
  DocsComponentsToggleRoute: typeof DocsComponentsToggleRoute
  DocsComponentsToggleGroupRoute: typeof DocsComponentsToggleGroupRoute
  DocsComponentsTooltipRoute: typeof DocsComponentsTooltipRoute
  DocsFirstStepsIntroductionIndexRoute: typeof DocsFirstStepsIntroductionIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/': {
      id: '/docs/'
      path: '/docs'
      fullPath: '/docs/'
      preLoaderRoute: typeof DocsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/components/tooltip': {
      id: '/docs/components/tooltip'
      path: '/docs/components/tooltip'
      fullPath: '/docs/components/tooltip'
      preLoaderRoute: typeof DocsComponentsTooltipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/components/toggle-group': {
      id: '/docs/components/toggle-group'
      path: '/docs/components/toggle-group'
      fullPath: '/docs/components/toggle-group'
      preLoaderRoute: typeof DocsComponentsToggleGroupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/components/toggle': {
      id: '/docs/components/toggle'
      path: '/docs/components/toggle'
      fullPath: '/docs/components/toggle'
      preLoaderRoute: typeof DocsComponentsToggleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/components/toast': {
      id: '/docs/components/toast'
      path: '/docs/components/toast'
      fullPath: '/docs/components/toast'
      preLoaderRoute: typeof DocsComponentsToastRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/components/textarea': {
      id: '/docs/components/textarea'
      path: '/docs/components/textarea'
      fullPath: '/docs/components/textarea'
      preLoaderRoute: typeof DocsComponentsTextareaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/components/text': {
      id: '/docs/components/text'
      path: '/docs/components/text'
      fullPath: '/docs/components/text'
      preLoaderRoute: typeof DocsComponentsTextRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/components/tag': {
      id: '/docs/components/tag'
      path: '/docs/components/tag'
      fullPath: '/docs/components/tag'
      preLoaderRoute: typeof DocsComponentsTagRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/components/tabs': {
      id: '/docs/components/tabs'
      path: '/docs/components/tabs'
      fullPath: '/docs/components/tabs'
      preLoaderRoute: typeof DocsComponentsTabsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/components/table': {
      id: '/docs/components/table'
      path: '/docs/components/table'
      fullPath: '/docs/components/table'
      preLoaderRoute: typeof DocsComponentsTableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/components/switch': {
      id: '/docs/components/switch'
      path: '/docs/components/switch'
      fullPath: '/docs/components/switch'
      preLoaderRoute: typeof DocsComponentsSwitchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/components/steps': {
      id: '/docs/components/steps'
      path: '/docs/components/steps'
      fullPath: '/docs/components/steps'
      preLoaderRoute: typeof DocsComponentsStepsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/components/skeleton': {
      id: '/docs/components/skeleton'
      path: '/docs/components/skeleton'
      fullPath: '/docs/components/skeleton'
      preLoaderRoute: typeof DocsComponentsSkeletonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/components/separator': {
      id: '/docs/components/separator'
      path: '/docs/components/separator'
      fullPath: '/docs/components/separator'
      preLoaderRoute: typeof DocsComponentsSeparatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/components/select': {
      id: '/docs/components/select'
      path: '/docs/components/select'
      fullPath: '/docs/components/select'
      preLoaderRoute: typeof DocsComponentsSelectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/components/rating': {
      id: '/docs/components/rating'
      path: '/docs/components/rating'
      fullPath: '/docs/components/rating'
      preLoaderRoute: typeof DocsComponentsRatingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/components/radio-card': {
      id: '/docs/components/radio-card'
      path: '/docs/components/radio-card'
      fullPath: '/docs/components/radio-card'
      preLoaderRoute: typeof DocsComponentsRadioCardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/components/radio': {
      id: '/docs/components/radio'
      path: '/docs/components/radio'
      fullPath: '/docs/components/radio'
      preLoaderRoute: typeof DocsComponentsRadioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/components/qr-code': {
      id: '/docs/components/qr-code'
      path: '/docs/components/qr-code'
      fullPath: '/docs/components/qr-code'
      preLoaderRoute: typeof DocsComponentsQrCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/components/progress-circle': {
      id: '/docs/components/progress-circle'
      path: '/docs/components/progress-circle'
      fullPath: '/docs/components/progress-circle'
      preLoaderRoute: typeof DocsComponentsProgressCircleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/components/progress': {
      id: '/docs/components/progress'
      path: '/docs/components/progress'
      fullPath: '/docs/components/progress'
      preLoaderRoute: typeof DocsComponentsProgressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/components/popover': {
      id: '/docs/components/popover'
      path: '/docs/components/popover'
      fullPath: '/docs/components/popover'
      preLoaderRoute: typeof DocsComponentsPopoverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/components/pin-input': {
      id: '/docs/components/pin-input'
      path: '/docs/components/pin-input'
      fullPath: '/docs/components/pin-input'
      preLoaderRoute: typeof DocsComponentsPinInputRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/components/password-input': {
      id: '/docs/components/password-input'
      path: '/docs/components/password-input'
      fullPath: '/docs/components/password-input'
      preLoaderRoute: typeof DocsComponentsPasswordInputRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/components/pagination': {
      id: '/docs/components/pagination'
      path: '/docs/components/pagination'
      fullPath: '/docs/components/pagination'
      preLoaderRoute: typeof DocsComponentsPaginationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/components/menu': {
      id: '/docs/components/menu'
      path: '/docs/components/menu'
      fullPath: '/docs/components/menu'
      preLoaderRoute: typeof DocsComponentsMenuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/components/input': {
      id: '/docs/components/input'
      path: '/docs/components/input'
      fullPath: '/docs/components/input'
      preLoaderRoute: typeof DocsComponentsInputRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/components/highlight': {
      id: '/docs/components/highlight'
      path: '/docs/components/highlight'
      fullPath: '/docs/components/highlight'
      preLoaderRoute: typeof DocsComponentsHighlightRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/components/heading': {
      id: '/docs/components/heading'
      path: '/docs/components/heading'
      fullPath: '/docs/components/heading'
      preLoaderRoute: typeof DocsComponentsHeadingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/components/field': {
      id: '/docs/components/field'
      path: '/docs/components/field'
      fullPath: '/docs/components/field'
      preLoaderRoute: typeof DocsComponentsFieldRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/components/dialog': {
      id: '/docs/components/dialog'
      path: '/docs/components/dialog'
      fullPath: '/docs/components/dialog'
      preLoaderRoute: typeof DocsComponentsDialogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/components/date-picker': {
      id: '/docs/components/date-picker'
      path: '/docs/components/date-picker'
      fullPath: '/docs/components/date-picker'
      preLoaderRoute: typeof DocsComponentsDatePickerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/components/combobox': {
      id: '/docs/components/combobox'
      path: '/docs/components/combobox'
      fullPath: '/docs/components/combobox'
      preLoaderRoute: typeof DocsComponentsComboboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/components/collapsible': {
      id: '/docs/components/collapsible'
      path: '/docs/components/collapsible'
      fullPath: '/docs/components/collapsible'
      preLoaderRoute: typeof DocsComponentsCollapsibleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/components/code-block': {
      id: '/docs/components/code-block'
      path: '/docs/components/code-block'
      fullPath: '/docs/components/code-block'
      preLoaderRoute: typeof DocsComponentsCodeBlockRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/components/clipboard': {
      id: '/docs/components/clipboard'
      path: '/docs/components/clipboard'
      fullPath: '/docs/components/clipboard'
      preLoaderRoute: typeof DocsComponentsClipboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/components/checkbox-card': {
      id: '/docs/components/checkbox-card'
      path: '/docs/components/checkbox-card'
      fullPath: '/docs/components/checkbox-card'
      preLoaderRoute: typeof DocsComponentsCheckboxCardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/components/checkbox': {
      id: '/docs/components/checkbox'
      path: '/docs/components/checkbox'
      fullPath: '/docs/components/checkbox'
      preLoaderRoute: typeof DocsComponentsCheckboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/components/carousel': {
      id: '/docs/components/carousel'
      path: '/docs/components/carousel'
      fullPath: '/docs/components/carousel'
      preLoaderRoute: typeof DocsComponentsCarouselRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/components/card': {
      id: '/docs/components/card'
      path: '/docs/components/card'
      fullPath: '/docs/components/card'
      preLoaderRoute: typeof DocsComponentsCardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/components/button': {
      id: '/docs/components/button'
      path: '/docs/components/button'
      fullPath: '/docs/components/button'
      preLoaderRoute: typeof DocsComponentsButtonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/components/breadcrumb': {
      id: '/docs/components/breadcrumb'
      path: '/docs/components/breadcrumb'
      fullPath: '/docs/components/breadcrumb'
      preLoaderRoute: typeof DocsComponentsBreadcrumbRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/components/avatar': {
      id: '/docs/components/avatar'
      path: '/docs/components/avatar'
      fullPath: '/docs/components/avatar'
      preLoaderRoute: typeof DocsComponentsAvatarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/components/alert': {
      id: '/docs/components/alert'
      path: '/docs/components/alert'
      fullPath: '/docs/components/alert'
      preLoaderRoute: typeof DocsComponentsAlertRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/components/accordion': {
      id: '/docs/components/accordion'
      path: '/docs/components/accordion'
      fullPath: '/docs/components/accordion'
      preLoaderRoute: typeof DocsComponentsAccordionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/charts/area-chart': {
      id: '/docs/charts/area-chart'
      path: '/docs/charts/area-chart'
      fullPath: '/docs/charts/area-chart'
      preLoaderRoute: typeof DocsChartsAreaChartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/first-steps/introduction/': {
      id: '/docs/first-steps/introduction/'
      path: '/docs/first-steps/introduction'
      fullPath: '/docs/first-steps/introduction/'
      preLoaderRoute: typeof DocsFirstStepsIntroductionIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DocsIndexRoute: DocsIndexRoute,
  DocsChartsAreaChartRoute: DocsChartsAreaChartRoute,
  DocsComponentsAccordionRoute: DocsComponentsAccordionRoute,
  DocsComponentsAlertRoute: DocsComponentsAlertRoute,
  DocsComponentsAvatarRoute: DocsComponentsAvatarRoute,
  DocsComponentsBreadcrumbRoute: DocsComponentsBreadcrumbRoute,
  DocsComponentsButtonRoute: DocsComponentsButtonRoute,
  DocsComponentsCardRoute: DocsComponentsCardRoute,
  DocsComponentsCarouselRoute: DocsComponentsCarouselRoute,
  DocsComponentsCheckboxRoute: DocsComponentsCheckboxRoute,
  DocsComponentsCheckboxCardRoute: DocsComponentsCheckboxCardRoute,
  DocsComponentsClipboardRoute: DocsComponentsClipboardRoute,
  DocsComponentsCodeBlockRoute: DocsComponentsCodeBlockRoute,
  DocsComponentsCollapsibleRoute: DocsComponentsCollapsibleRoute,
  DocsComponentsComboboxRoute: DocsComponentsComboboxRoute,
  DocsComponentsDatePickerRoute: DocsComponentsDatePickerRoute,
  DocsComponentsDialogRoute: DocsComponentsDialogRoute,
  DocsComponentsFieldRoute: DocsComponentsFieldRoute,
  DocsComponentsHeadingRoute: DocsComponentsHeadingRoute,
  DocsComponentsHighlightRoute: DocsComponentsHighlightRoute,
  DocsComponentsInputRoute: DocsComponentsInputRoute,
  DocsComponentsMenuRoute: DocsComponentsMenuRoute,
  DocsComponentsPaginationRoute: DocsComponentsPaginationRoute,
  DocsComponentsPasswordInputRoute: DocsComponentsPasswordInputRoute,
  DocsComponentsPinInputRoute: DocsComponentsPinInputRoute,
  DocsComponentsPopoverRoute: DocsComponentsPopoverRoute,
  DocsComponentsProgressRoute: DocsComponentsProgressRoute,
  DocsComponentsProgressCircleRoute: DocsComponentsProgressCircleRoute,
  DocsComponentsQrCodeRoute: DocsComponentsQrCodeRoute,
  DocsComponentsRadioRoute: DocsComponentsRadioRoute,
  DocsComponentsRadioCardRoute: DocsComponentsRadioCardRoute,
  DocsComponentsRatingRoute: DocsComponentsRatingRoute,
  DocsComponentsSelectRoute: DocsComponentsSelectRoute,
  DocsComponentsSeparatorRoute: DocsComponentsSeparatorRoute,
  DocsComponentsSkeletonRoute: DocsComponentsSkeletonRoute,
  DocsComponentsStepsRoute: DocsComponentsStepsRoute,
  DocsComponentsSwitchRoute: DocsComponentsSwitchRoute,
  DocsComponentsTableRoute: DocsComponentsTableRoute,
  DocsComponentsTabsRoute: DocsComponentsTabsRoute,
  DocsComponentsTagRoute: DocsComponentsTagRoute,
  DocsComponentsTextRoute: DocsComponentsTextRoute,
  DocsComponentsTextareaRoute: DocsComponentsTextareaRoute,
  DocsComponentsToastRoute: DocsComponentsToastRoute,
  DocsComponentsToggleRoute: DocsComponentsToggleRoute,
  DocsComponentsToggleGroupRoute: DocsComponentsToggleGroupRoute,
  DocsComponentsTooltipRoute: DocsComponentsTooltipRoute,
  DocsFirstStepsIntroductionIndexRoute: DocsFirstStepsIntroductionIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
